concord-consortium/report-service

functions/src/api/import-structure.ts
The idea is to build a document path from the host (eg: `authoring.concord.org`) and a hash of the resource url eg: `https://authoring.concord.org/activities/23`.  The path is then:
`/sources/${hostKey}/resources/${contentKey}`
We write the whole serialized activity as the document data.
[#166063708]
https://www.pivotaltracker.com/story/show/166063708
=> First pass at the import-structure function.

functions/src/api/helpers/lara-types.ts, functions/src/api/helpers/paths.ts
We were doing the same URL munging in both LARA and the report service to get `source_key`s.
Some of the portal entities (`answers`) didn't actually have URLs to support computing the `source_key` in FireStore.
This commit changes the interfaces to require common and explicit keys.
[#166063708]
https://www.pivotaltracker.com/story/show/166063708
=> Use uniform keys for LARA entities (source_key, id).

firestore.rules
We save the teachers settings for the offering at this FireStore path:
/sources/${sourceId}/user_settings/${platformUserId}/offering/${contextId}
⬆ This lets us limit access to report settings based on user and offering.
The FireStore rules are setup to allow unfettered access to:
`/sources/fake.portal/user_settings/1/offering/class123`
⬆ This let us test the report settings with fake portal data, without a valid JWT.
https://www.pivotaltracker.com/story/show/166240880
=> [#166240880] FireStore: Save assignment level report settings

query-creator/template.yaml
The "internal server error" we saw was actually not caused by the function but rather by the api gateway timing out.  The default timeout is 3 seconds, I increased this to 300 (5 minutes).
=> Increase api gateway timeout from 3 seconds to 300 seconds [#173924040]

firestore.rules
This modifies the answer rules such that
1. A learner can now update and create content, but only within their current class
2. Unauthenticated users can read, update and create any content with a run key. I arbitrary required a minimum of 10 characters for the run-key, to prevent any code that might accidentally use an empty string, or something non-random like the class id.
=> Update learner and anonymous answer rules

query-creator/create-query/app.js, query-creator/create-query/steps/firebase.js
1. The body of the try/catch error wrapper needs to be a string (it was an object which caused the "Internal server error" message)
2. The rethrown error in the getResource Firebase call referenced an unknown variable
=> Fixed two errors found when doing prod deployment

functions/README.md, functions/src/auto-importer.ts, functions/src/shared/s3-answers.ts
This supports the Activity Player by using the LTI properties for logged in users that can be combined to identify a learner-assignment (platform_id, resource_link_id and platform_user_id) to find the answers collection and to create the parquet files. For anonymous users we still use the runKey.
For a logged-in user launching from the portal (LARA or Activity Player) we now save parquet files to:
partitioned_answers/[escaped_resource_id]/[escaped-platform_id]/[escaped_resource_link_id]/[platform_user_id].parquet
For an anonymous user (LARA or AP):
partitioned_answers/[escaped_resource_id]/anonymous/no-resource-link/[run-key].parquet
A few other changes needed to be made to support finding answers using these properties, and to support the differences in how the AP saves answers (some …
=> Support Activity Player

README.md, functions/package.json, functions/src/shared/s3-answers.ts, scripts/README.md, scripts/export-answers.js
This updates the bulk-upload of all answers to support the LTI metadata and new directory structure of the update-answers Firestore function.
=> Support LTI in export-answers script

query-creator/README.md, query-creator/samconfig.toml
This PR updates `samconfig.toml`  so that it includes the `profile` parameter with value `QueryCreatorLocalTestUser` when running `sam local start-api`.  It also updates the readme with more details about running query creator locally.
=> 178026269 run local

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This PR adds question prompts to the Athena query generated in `generateSQL`.  Note that the prompts are only added to a single column for the multiple choice, image, and open response questions (image and open response are made up of more than one column).  A null value is added for additional columns since the UNION query requires an identical number of fields.
Example query with prompts:
```
-- activity-activity_20654
WITH activities AS ( SELECT * FROM "report-service"."activity_structure" WHERE structure_id = 'b1e8fe05-c62d-4d3c-b999-6bc61fa9c826' )
SELECT
activities.questions['multiple_choice_12818'].prompt AS multiple_choice_12818_choice,
activities.questions['multiple_choice_12843'].prompt AS multiple_choice_12843_choice, …
```
=> Add question prompts to query

query-creator/create-query/steps/firebase.js
Activity Player activities that have been imported from LARA have a resource url like
https://activity-player.concord.org/?activity=https%3A%2F%2Fauthoring.staging.concord.org%2Fapi%2Fv1%2Factivities%2F20753.json&firebase-app=report-service-dev
this changes the above to
https://authoring.staging.concord.org/activities/20753
so that the resource be properly returned by the report service api.
=> Support Activity Player runnable urls for imported activities

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This PR adds the question percent complete to the Athena query generated in `generateSQL`.   The unit test for `generateSQL` has also been expanded to include the percent complete. 
Example query with percent complete:
```
-- activity-activity_20654
WITH activities AS ( SELECT *, cardinality(questions) as num_questions FROM "report-service"."activity_structure" WHERE structure_id = '029ce969-1bb8-4eaf-9f98-e1c6c6277fd9' )
SELECT
null as num_questions,
null as num_answers,
null as percent_complete,
activities.questions['multiple_choice_12818'].prompt AS multiple_choice_12818_choice,
activities.questions['multiple_choice_12843'].prompt AS multiple_choice_12843_choice,
activities.questions['multiple_choice_12845'].prompt AS multiple_choice_12845_choice, …
```
=> 177955279 query creator percent complete

scripts/README.md, scripts/export-answers.js
This adds the ability to filter the uploading of answers by a regex on the `created` property in an answer.
This is conservative: if an answer does not have a `created` field it will be uploaded, and it only takes one answer in a user's session that matches the regex (or has `created` missing) to upload the entire learner-assignment collection.
Also updated the readme with more information on running the script, including probably-pedantically-detailed Lightsail instructions.
=> Add `created` regex to export script

query-creator/create-query/steps/aws.js, query-creator/create-query/steps/firebase.js, query-creator/create-query/tests/unit/test-handler.js
This PR expands Athena SQL query for multiple choice questions to include:
- show all answers if question supports multiple answers
- show correct/wrong status if question has a valid answer defined
In doing so, the following types of multiple choice questions are now supported:
- multiple choice where user can enter single answer and correct answer is defined
- multiple choice where user can enter single answer and no correct answer is defined
- multiple choice where user can enter multiple answers and correct answer is defined
- multiple choice where user can enter multiple answers and no correct answer is defined
Unit tests have also been expanded to include these new cases. EDIT: I also used the `denormalizedResource` instead of the `resource` inside of `generateSQL` to access …
=> 173668043 multiple choice query updates

query-creator/README.md, query-creator/create-query/steps/aws.js, query-creator/create-query/steps/firebase.js, query-creator/create-query/tests/unit/test-handler.js
This PR adds the question type to the denormalizedResource which is then used to determine the question type when making the Athena query (rather than using the id).  This allows Activity Player managed interactive questions to work properly in queries.
=> Add support for activity player managed interactives in query creation

query-creator/README.md, query-creator/create-query/app.js, query-creator/create-query/steps/aws.js, query-creator/create-query/steps/env-vars.js, query-creator/create-query/steps/firebase.js, query-creator/create-query/steps/request.js, query-creator/create-query/tests/unit/test-handler.js, query-creator/template.yaml
Use JWT to fetch and uploaded paginated learners
This updates the expected request from the portal to be using the JWT query, which then allows us to request learner details from the portal.
The function `aws.fetchAndUploadLearnerData` uses the JWT to request the leaners from the portal, and uploads each batch as it comes. (We no longer try to keep the learners in memory and upload them later, as we want to support requests of up to a million learners.)
Previously, each runnable got a queryId, and we uploaded the learners for that runnable to
`{s3_bucket}/learners/{queryId}/{queryId}.json`
Now, because our learners might be fetched in multiple parts, we upload to
```
{s3_bucket}/learners/{queryId}/{uuid-1}.json
{s3_bucket}/learners/{queryId}/{uuid-2}.json
...
```
We still keep one queryId …
=> Get learners with JWT

results-loader/package.json
This is a temporary solution to at least allow Mac devs to run the results-loader using https by running `npm run start:secure` and having the cert/key files in a `.localhost-ssl` folder inside their home directory.  Windows users need to manually change the path to the cert/key files (which works fine for me), but this should, for now, make it easier for devs running on Macs.  Eventually this should be replaced by the platform-independent solution that is on a branch in the `starter-projects`, but as discussed, that solution depends on a release of `webpack-dev-server`.  I think this is a good tweak to get in to make work on the results-loader a little easier.
=> Add secure run script for Mac users

query-creator/README.md, query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This adds the following fields to the table returned by the SQL query:
```
runnable_url,
learner_id,
student_id,
user_id,
student_name,
username,
school,
class,
class_id,
permission_forms,
last_run,
teacher_user_ids,
teacher_names,
teacher_districts,
teacher_states,
teacher_emails,
```
Here is an example of a query produced by these changes, which can be run in Athena on staging:
```
-- activity-activity_20654
WITH activities AS ( SELECT *, cardinality(questions) as num_questions FROM "report-service"."activity_structure" WHERE structure_id = 'e49ac023-e318-49ff-9260-5c4b1c461ca7' )
SELECT
null as runnable_url,
null as learner_id,
null as student_id,
null as user_id,
null as student_name,
null as username,
null as school,
null as class,
null as class_id,
null as …
```
=> Update SQL to include learner metadata

results-loader/package.json, results-loader/src/components/app.scss, results-loader/src/components/app.tsx, results-loader/src/utils/results-utils.ts
This PR gets the Athena workgroup resources based on the portal access token and firebase JWT.  It also gets the resource credentials for the first resource in the resource list.  Changes include:
- add `@concord-consortium/token-service`
- get list of athena workgroup resources and set 0th resource as the current resource
- display information about current resource in app
- get the credentials for the current resource and display the credential information in the app
- improve and unify the status messages at each step.  This makes it easier to follow the render code and easier to refactor chunks out into components if needed.
Note that when we call `listResources`, I'm setting the `tool` property to `example-app`.  Obviously this is wrong and need to be some string that is used by …
=> Get athena workgroup resources and resource credentials

results-loader/package-lock.json, results-loader/package.json, results-loader/src/components/app.tsx, results-loader/src/components/query-item.scss, results-loader/src/components/query-item.tsx
This PR gets the list of queries for the current workgroup and display information about these queries to the user in list form.  Changes include:
- request list of query execution ids for current workgroup
- for each query execution id, get query execution information
- using the query execution information, display the query date, query URI (won't be needed long-term, but is useful to show uniqueness for now), and present a button for downloading CSV (nothing is implemented here yet - that will be next).
=> Get query execution list and query execution, display to user

researcher-reports/README.md, researcher-reports/package.json, researcher-reports/src/components/header.tsx, researcher-reports/src/components/query-item.scss, researcher-reports/src/components/query-item.tsx, researcher-reports/src/index.html, researcher-reports/src/utils/translation/README.md
This PR changes the name from "Results Loader" to "Researcher Reports" in a few more locations in the project and restores the QueryItem component that got lost in the last merge.
=> Report name update, Restore QueryItem component

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This PR adds support for questions of type `iframe_interactive` and unknown question types when generating the Athena query in the query creator lambda function.  When either are encountered, add a column that displays the full answer JSON.
Result query:
```
-- activity-activity_21051
WITH activities AS ( SELECT *, cardinality(questions) as num_questions FROM "report-service"."activity_structure" WHERE structure_id = 'd98e3905-814d-453c-8bc1-816af3b0e762' )
SELECT
null as runnable_url,
null as learner_id,
null as student_id,
null as user_id,
null as student_name,
null as username,
null as school,
null as class,
null as class_id,
null as permission_forms,
null as last_run,
null as teacher_user_ids,
null as teacher_names,
null as teacher_districts,
null as …
```
=> Add support for iframe_interactive type in query

query-creator/create-query/app.js, query-creator/create-query/package-lock.json, query-creator/create-query/package.json, query-creator/create-query/steps/aws.js, query-creator/create-query/steps/request.js, query-creator/create-query/steps/token-service.js, query-creator/template.yaml, researcher-reports/src/utils/results-utils.ts
This adds the finding/creation of a resource using the token-service, the creation of the appropriate workgroup in Athena, and the ability to execute the query directly on Athena.
Notes:
1. PR for the token-service is [here](https://github.com/concord-consortium/token-service/pull/49), I've assumed we'll release it as `^2.0.0-pre.2` when it is approved
2. New tool name is `researcher-report`, I updated it in the researcher-report project as part of this PR
3. New permissions for the Lambda Role were added to the template, based on what I got working by adding to the `QueryCreatorLocalTestUser` user. The policy I created for that user is [here](https://console.aws.amazon.com/iam/home?region=us-east-1#/policies/arn:aws:iam::816253370536:policy/QueryCreatorPolicyForLocalTesting$jsonEditor). …
=> Use token service to create resource + workgroup; execute query on Athena

query-creator/create-query/app.js, query-creator/create-query/steps/env-vars.js, query-creator/samconfig.toml, query-creator/template.yaml, researcher-reports/src/components/app.tsx, researcher-reports/src/utils/results-utils.ts
This adds the redirect to the researcher-reports app after the queries have been kicked off in Athena (unless `debugSQL=true` is in the query params).
The researcher-reports url is defined in an env variable set on deploy. This will not usually need to change for different portals, but it seemed helpful to have staging point to the master branch of the reports app.
When the query-creator loads, it extracts the portal url from the learner-api url that is passed in by the JWT. It then opens the researcher-reports with `?portal=purtalUrl`. The researcher reports app is updated to find this query param and use it for authentication with the portal. When the app later strips out the token, we preserve this param because we later need to make a request to the same portal for the JWT.
If the …
=> Redirect to researcher reports

researcher-reports/src/components/query-item.tsx
This PR adds the query status to the researcher reports app.  The status is obtained from the `QueryExecution` object and displayed to the user for each query in the results list.
=> Add completion status to the researcher report

researcher-reports/src/components/app.scss, researcher-reports/src/components/app.tsx, researcher-reports/src/components/query-item.scss
This PR improves the layout and text in the researcher report so it is more clear where the reports are and what the status/debugging information is for.  Changes include:
- move reports above debug/status info
- use "report" instead of "query" in user-facing text
- add border and title around report and debug/status sections to make them more clear
=> Researcher Report: Improve layout and text in report and status/debug sections

query-creator/create-query/app.js, query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js, researcher-reports/src/components/query-item.tsx
This PR adds the resource name and resource type to the top of the Athena query as a comment.  This can then be used in the Researcher Report to display the name and type to the user.  The full query contents are pulled from the execution info and we then parse out the name and type.  If we find them, we show them to the user.  The resource id is still added as a comment if we are in debug mode.
Example query:
```
-- name Example OR, MC, and IQ managed interactive questions 
-- type activity
WITH activities AS ( SELECT *, cardinality(questions) as num_questions FROM "report-service"."activity_structure" WHERE structure_id = '1029f7ea-4af7-4c6c-83a8-0abe45487d4f' )
SELECT
null as runnable_url,
null as learner_id,
null as student_id,
null as user_id,
null as …
```
=> 178546257 resource name

query-creator/create-query/app.js, query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This PR adds a `usageReport` URL parameter to Query Creator.  When set to true, the `generateSQL` function will create a smaller query that does not include the answer data.  
To test, pull this branch, run a local version of the query creator (`sam build`, `sam local start-api`) and then login to the learner report:
https://learn-report.staging.concord.org/report/learner
Enter filter values and then press the "SAM Query Creator Local (debugSQL usageReport)" button.  This will generate the SQL to make a usage report.
We will also need to add a final button to the learner report page that launches the actual lambda, but that can wait until after this PR is merged.  
Example usageReport query:
```
-- id activity-activity_21026
-- name Example OR, MC, and IQ managed interactive questions 
-- …
```
=> Query Creator: Add usageReport URL param to create report with no answers

researcher-reports/src/components/app.tsx, researcher-reports/src/utils/results-utils.ts
This tests to see if we're running on the production url, and, if so, use "production" tokenServiceEnv. Otherwise default to "staging".
=> Use production token service on production

query-creator/create-query/app.js, query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This PR handles unreportable runnables (runnables where we cannot access a resource from Firebase).  In this case, we strip out all answer and completion information from the SQL query and generate a report that contains only learner data (including the last run info).  This report is essentially the usage report without the completion information.  Changes include:
- when we cannot access a valid resource, we still call `generateSQL`, but attempt to create a simplified report with only learner data.
- add unit tests
Some notes:
- the same report is generated for both the details and the usage report.  I originally implemented skipping unreportable runnables when the user requested a details report, but in practice this felt confusing and is likely to leave a user thinking that the report …
=> Query Creator: Handle unreportable runnables in query creation

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This PR adjust the Athena SQL query in `generateSQL` so that it can handle learners who we do not have answer data for.  This is based off of the query presented by @scytacki on Slack.  A few things that still merit testing or improving:
- in some of the queries there are excess line breaks (not sure if we care)
- probably should be tested more with real data before merging (the queries work, but I haven't set up the staging case yet where we have users who don't have answers so we can ensure that they appear in the report).
=> Add query support for learners with no answers

query-creator/README.md, query-creator/create-query/app.js, query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js, query-creator/env.sample.json, query-creator/samconfig.toml, query-creator/template.yaml
This constructs a url to the Portal Report for every iframe interactive, if the user has answer data for the model.
The url that is constructed looks like:
```
https://portal-report.concord.org/branch/master/index.html
?auth-domain=[https://learn.staging.concord.org | https://learn.concord.org | other portal url]
&firebase-app=[report-service-dev | report-service-pro]
&iframeQuestionId=[model-id, eg. "mw_interactive_210741"]
&class=[{portal-url}/api/v1/classes/{class-id}]
&offering=[{portal-url}/api/v1/offerings/{offering-id}]
&studentId=[student-id]
```
For this to work we need the `offering-id`, which wasn't previously passed back from the portal when requesting learner details, and has now been added as a PR. The leaners table must also be updated to support this.
An example query that …
=> Add model urls to Athena query

firestore.rules, tests/student-work-rules.test.js
These JWTs have a class_hash and a target_user_id.
The target_user_id should match the platform_user_id of the document being requested.
The class_hash should match the context_id.
This way the researcher is restricted to just the student's work in a specific class.
=> update rules to support new researcher jwts

.firebaserc, firestore.rules, tests/feedback-rules.test.js
The portal-report loads in the feedback even when just looking at a single answer
That code could be optimized to not request the feedback, but it also seems like it
would be useful if a researcher could open the student report and see the feedback given to the student.
=> researchers need access to feedback as well

query-creator/README.md, query-creator/create-query/app.js, query-creator/create-query/steps/aws.js
The goal of this PR is to be able to run learner log queries optionally leaving out learner meta data.
1. 56b9800 : 2021-12-09 :  Update instructions for developing with local docker using ngrok public proxy.
[PT Story #180559584](https://www.pivotaltracker.com/story/show/180559584)
=> 180559584 Athena Log queries are decoupled from learner information.

query-creator/README.md, query-creator/create-query/app.js, query-creator/create-query/steps/aws.js
- Rename query param `endpointOnly` to `narrowLearners`. It makes sense for the portal learner endpoint to use `endpoint_only` for its param, but here that param name seems vague. Renamed for clarity, and updated the docs.
- If the query param `narrowLearners` is true, The select statement will only include `log.*` columns, because we didn't run the reconsituting learner queries. This just reduces empty values in the CSV file that is created.
[#180559584]
=> 180559584 -- limit CSV columns when reporting on log data only.

query-creator/create-query/steps/aws.js, query-creator/create-query/steps/env-vars.js, query-creator/env.sample.json, query-creator/samconfig.toml, query-creator/template.yaml
Query-Creator:
The Log database name changes from staging to production.
We need to put the DB name in an ENV var to be configured in cloud formation.
[#180969564]
https://www.pivotaltracker.com/story/show/180969564
(FWIW this has already been deployed to the production query-creator stack on AWS)
=> 180969564 : Query-Creator: Database Name param

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/aws.js
The time based query was using the old Postgres string date format whereas Athena needed a unix timestamp.
=> Fixed time based user log queries [#184157275]

.github/workflows/firestore-and-query-creator-tests.yml, .github/workflows/researcher-reports.yml, query-creator/create-query/steps/request.js, researcher-reports/package-lock.json, researcher-reports/package.json, researcher-reports/webpack.config.js
This changes the !== undefined runnable url filter to non-falsy so that runnable urls with null values are also filtered.
**NOTE**: this PR also updates the test matrix to use node 16 based on a required upgrade message from the Firebase CLI which when cased node-sass to break.  The node-sass package isn't being used in this project so I removed it instead of converting it to use dart-sass.
=> fix: Filter out null runnable urls [PT-185994904]

firestore.rules
NOTE: this also adds a missing ap_runs matcher that exists on both staging and production and must have been added there via the web UI.
=> feat: Add research read access to classes [PT-187154204]

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This adds an url to view the open response via the portal dashboard, mainly to hear the recorded audio answer.  Unlike newer question interactives open response only records the text as the answer and not the full interactive state.  Because of this there is no way to check if the open response has an audio answer.  Furthermore if the open response only has an audio answer there is no recorded text answer.
To add the url two things had to be changed with the details report:
1. Instead of joining learners to answers the order was switched and answers are joined to learners.  This allows learners that have only audio responses and no text response to still show in the report.
2. If the open response has no answer fall back to pulling the answerSourceKey parameter needed by the portal to …
=> feat: Add open response url in the details report using sourceKey fallback [PT-181870149]

server/lib/report_server_web/controllers/page_controller.ex, server/lib/report_server_web/controllers/page_html/config.html.heex, server/lib/report_server_web/router.ex, server/lib/report_server_web/token_service.ex
I needed to add this to figure out why the production server wasn't walking to the production token service.  You'll see the fix for that in TokenService#get_env.
=> Added /config endpoint to expose non-secret configuration options

server/lib/report_server_web/live/report_live/query.ex
The form was not being updated within the query but rather set at the top level assigns.
=> fix: Post processing step checkboxes not accepting initial click [PT-187486891]

server/lib/report_server_web/auth.ex, server/lib/report_server_web/components/layouts/app.html.heex
This is to avoid confusion of which portal the user may be logged into.
=> feat: Add portal domain to report-server header

server/lib/report_server_web/components/layouts/app.html.heex, server/lib/report_server_web/token_service.ex, server/mix.exs
The portal parameter generated by the query-creator post uses the report server urls and not the main portal urls.
This also adds the current application version number to the page header to make deployment checks easier.
=> fix: Add report portal urls to production portal url check

server/lib/report_server/post_processing/job_server.ex, server/lib/report_server/post_processing/steps/glossary_audio_links.ex
This is the start of the glossary audio link post processing step.  It defines the step and, for now, always adds the bare audio demo link to the csv.
=> feat:  Add placeholder for glossary audio link post-processing step [PT-187885500]

functions/src/api/get-plugin-states.ts, functions/src/index.ts
This returns a (possibly empty) map of document ids to parsed plugin states for a remote endpoint under a source.
=> feat: Add api endpoint to get plugin states [PT-187885524]

server/assets/js/codap-plugin.ts
This ensures that the table is shown (as there is no api endpoint to just show an existing table.
=> fix: Always create table on plugin queries [PT-188522108]

server/README.md, server/config/runtime.exs, server/docker-compose.yml, server/lib/report_server/dashboard/stats_server.ex, server/lib/report_server_web/live/page_live/home.ex, server/lib/report_server_web/live/page_live/home.html.heex, server/mix.exs
The stats server currently won't work on staging due to security group issues so this lets us disable it there.
=> feat: Added env var to disable stats server

server/Dockerfile
Since the CODAP plugin uses npm to get the plugin api the release Dockerfile needs to have npm available
=> build: Added npm install to Dockerfile

server/lib/report_server/application.ex, server/lib/report_server_web/live/codap_plugin_live/index.ex, server/mix.exs
The security ingress rules on production do not currently allow the report server to connect to the ngss db so it is being temporarily removed from the list of servers.
NOTE: the jump from `pre-1` to `pre-3` was because I had updated staging and production to `pre-2` and then needed to make this fix and so I needed a new docker image tag to redeploy it.
=> fix: Disable ngss server for now

server/config/dev.exs, server/lib/report_server/reports/tree.ex
This prevents the run function of each report from being cached in memory which would require a restart of the server on any change to that function.
=> feat: Disable report tree cache in dev mode

server/lib/report_server/reports/resource_metrics_details.ex, server/lib/report_server/reports/resource_metrics_summary.ex, server/lib/report_server/reports/teacher_status.ex, server/lib/report_server/reports/tree.ex
Updates the three report queries.
Minor changes to the teacher report, but large rewrites to the resource summary and detail.
Properly uses the tables to look at offerings, rather than leaning on the report_learners table for everything.
One remining issue is determining grade level.  Not sure if the query is wrong or if the canned samples simply do not have grade levels specified.
Updates names and descriptions of the reports to what is in the design doc.
=> Query refinement

server/lib/report_server/reports/resource_metrics_summary.ex
This ensures resources that have not been assigned are still shown.
=> fix: Update resource metrics summary report to use left join

server/lib/report_server/reports/tree.ex, server/lib/report_server_web/components/custom_components.ex, server/lib/report_server_web/live/new_report_live/index.html.heex
Make reports more self-documenting by displaying the description (aka subtitle) next to each.
=> Show descriptions next to report links

server/lib/report_server/reports/report.ex, server/lib/report_server/reports/report_filter.ex, server/lib/report_server/reports/report_filter_query.ex, server/lib/report_server/reports/report_query.ex, server/lib/report_server/reports/tbd_report.ex, server/lib/report_server/reports/tree.ex, server/lib/report_server_web/live/new_report_live/form.ex, server/lib/report_server_web/live/report_run_live/show.ex, server/lib/report_server_web/live/report_run_live/show.html.heex, server/test/report_server/report_filter_query_test.exs, server/test/report_server/report_query_test.exs, server/test/report_server/reports_test.exs
PT-188589623
Adds 'Permission forms' to the set of filters supported.  Includes appropriate queries for permission forms to be limited by other filters and for other filters to be limited by permission forms.
Updates some of the other quries to avoid joining the same field twice where not needed.
Adds a 'filters_included' field to reports so not all existing filters need to be included on each report.  The 3 existing reports do not use Permissions forms filtering.
Improve error handling in `get_sql`.  Now returns a tuple with `:ok` or `:error`.
Adds some (not exhaustive) tests for `ReportQuery` and `ReportFilterQuery`.
**Skips** 7 tests that were failing.
=> Permission form filtering

server/lib/report_server/reports/report_query.ex, server/lib/report_server/reports/resource_metrics_details.ex, server/lib/report_server/reports/resource_metrics_summary.ex, server/lib/report_server/reports/teacher_status.ex, server/lib/report_server_web/components/custom_components.ex, server/lib/report_server_web/live/report_run_live/show.ex, server/lib/report_server_web/live/report_run_live/show.html.heex, server/test/report_server/report_query_test.exs
PT-188589069: only show the first 100 rows of queries.
No longer stores the full results of queries in memory after they are displayed.
This means query has to be re-run for sort changes and downloads.
We want the database server to do the query with a `limit`, which means it has to do the sorting as well so that we get the correct top rows.  So this includes a refactor to construct the appropriate `order by` clauses for any choice of sorting.
A separate query is contructed and executed (once, since sorts/downloads shouldn't affect it) to determine the total number of rows.
Also refactored the `ReportQuery` struct to have a list of cols rather than a single `select` string. This turned out not to be necessary but seems like it might be useful in the future so I kept it in.
Testing note: …
=> Limit how many rows of report on shown in live view.

server/lib/report_server/reports/report_filter.ex, server/lib/report_server/reports/report_filter_query.ex, server/lib/report_server_web/components/custom_components.ex, server/lib/report_server_web/live/new_report_live/form.ex, server/lib/report_server_web/live/new_report_live/form.html.heex
UI refinement - part of  PT-188527665
* Changes in filters cause cascading changes to filters below them.  This includes updating the list of options in the pulldown, and removing any selected values that no longer are allowed by the upstream filters.
* Update placeholder text in the inputs to show if there are options to choose from.
* Fix a crash when changing the "type" pulldown menu back to `Select a filter...`
* Allow teacher search to match on substrings like 'john s' , rather than testing for substrings of first name and last name separately.
* When table is too wide, allows page to get scroll bar rather than scrolling just the table. This keeps the scrollbar visible.
=> Cascading filters & UI misc

server/assets/js/app.ts, server/config/dev.exs, server/mix.exs
This uses a new feature in phoenix_live_reload to inject the server logs into the client console for easier debugging.  This only is enabled in dev.
=> dev: Add server logs to the browser console

server/lib/report_server/reports/portal/resource_metrics_details_report.ex
Changes the query to show the grades of the classes to which the resource has been assigned, rather than the grades associated with the reource itself.
=> Change resource detail report grades column to class grades

server/lib/report_server/reports/report_filter.ex, server/lib/report_server/reports/report_filter_query.ex, server/lib/report_server_web/live/new_report_live/form.ex, server/lib/report_server_web/live/new_report_live/form.html.heex
PT-188527665
Fix a few UI problems.
- If a filter exists, but no values are chosen, return no results, instead of a potentially very long list.
- Reset selection menu when filter type is changed.
- Include query string in placeholder text, for clarity
- Allow searching cohort with 1-2 characters, since all values are shown with no characters anyway
- Changing filter type removes list of options of previous type
=> Fix more ux issues

server/lib/report_server_web/components/custom_components.ex
This adds the following note to the Athena reports once they succeed:
"Note: Report preview and JSON download are not supported for this report type."
=> feat: Add report preview note to Athena reports [PT-188700907]

server/lib/report_server/reports/portal/resource_metrics_details_report.ex, server/lib/report_server/reports/portal/teacher_status_report.ex
Addresses QA comment in PT-188613525
Count of number of runs in details report was wrong due to lack of `distinct` in query.
Teacher status report appeared to be correct but adding `distinct` on runs there as well in case untested cases or future updates cause retrieval of multiple rows with the same run id.
=> Fix number of runs in reports

server/lib/report_server/reports/athena/learner_data.ex, server/lib/report_server/reports/report_utils.ex, server/lib/report_server_web/live/report_run_live/show.ex
This fix causes the query to exit early with a "No learner data found" error when there are no learners found matching a query.
=> fix: Added check for no learners [PT-188527607]

server/lib/report_server/reports/athena/resource_data.ex, server/lib/report_server/reports/athena/shared_queries.ex
This fixes a bug in the code that generated the question columns in the shared query.  The inner loop of the reducer was mapping its result instead of reducing on it.  This caused enormously large nested lists to be created when there were a large number of columns.  These nested lists caused geometric slowdown of each reduce pass as the lists increased in size.
The fix for this was to reduce instead of mapping in the inner reducer - this causes the list to only increase in side proportional to the number of columns.
I also added a flag to skip retries of the resource if the Firebase function returns 500, which it does when the function does not provide a source parameter that is correct.
=> fix: Crash on large requests [PT-188748565]

server/lib/report_server/reports/athena/learner_data.ex, server/lib/report_server/reports/athena/resource_data.ex, server/lib/report_server/reports/athena/shared_queries.ex, server/lib/report_server/reports/athena/student_actions_with_metadata_report.ex
Converts learner and resource data from a map to a list and adds a question_order field to the denormalized resource.
The original JavaScript used a hash where the key ordering is maintained in insertion order.  In Elixir the key order is alphabetic so lists must be used to maintain ordering of both resources and questions within denormalized resources.
This also fixes a deprecation warning in the Floki library when extracting the text from the student answer.
=> fix: Resource ordering in shared queries [PT-188527607]

server/lib/report_server/reports/athena/shared_queries.ex
This line was accidentally removed while debugging the column ordering issue.
=> fix: Accidentally removes List.reverse call [PT-188527607]

server/config/dev.exs, server/lib/report_server_web/live/new_report_live/post_processing.ex, server/lib/report_server_web/live/report_run_live/show.ex, server/lib/report_server_web/live/report_run_live/show.html.heex
This integrates the existing post-processing facilities with the new reports.  The jobs are still saved on S3 instead of using a new table so that the existing post-processing from the portal launched reports work without updates.
=> feat: Added post processing to new report [PT-188613581]

server/lib/report_server/post_processing/steps/clue_link_to_work.ex
This is needed so the portal can verify the researcher has access to the log event.
=> fix: Add targetUserId to CLUE url [PT-188520218]

server/lib/report_server_web/aws.ex, server/lib/report_server_web/live/page_live/home.html.heex, server/lib/report_server_web/live/report_live/index.ex, server/lib/report_server_web/live/report_live/query.ex, server/lib/report_server_web/router.ex
This is the first step in a three step process to remove the old reports and replace the /reports url with the new reports.
Once this is live the existing query-creator Firebase function can be updated to redirect to /old-reports.  Once that is live then a follow on PR will rename /new-reports to /reports.
Then, the portals can then be updated to remove the report links from the admin and add the report link in the sidebar to point to /reports.
Finally, a follow on PR will remove all the /old-reports code that is no longer needed.
=> fix: Move /reports to /old-reports [PT-188779638]

server/lib/report_server_web/components/custom_components.ex, server/lib/report_server_web/live/new_report_live/form.ex, server/lib/report_server_web/live/new_report_live/index.html.heex, server/lib/report_server_web/live/page_live/home.html.heex, server/lib/report_server_web/live/report_run_live/index.ex, server/lib/report_server_web/live/report_run_live/index.html.heex, server/lib/report_server_web/live/report_run_live/show.ex, server/lib/report_server_web/redirect_to_reports.ex, server/lib/report_server_web/router.ex
This updates all /new-reports links to /reports and adds a plug to automatically redirect /new-report urls to /reports so test links don't break.
=> feat: Move /new-reports to /reports [PT-188779638]

server/lib/report_server/reports/report_filter_query.ex
PT-188818747
Fixes column name which was `aci` in JOIN clause but `aci_cohort` in ON clause.
=> Fix column name in query

server/lib/report_server/reports/tree.ex, server/lib/report_server_web/live/page_live/home.ex, server/lib/report_server_web/live/page_live/home.html.heex, server/lib/report_server_web/live/report_live/index.html.heex
This adds direct links to reports to the homepage along with the run links and comments out the empty CODAP reports.
=> feat: Added reports to homepage [PT-188779638]

server/lib/report_server_web/live/report_run_live/index.ex
The server was throwing a 500 error when the liveview mounted without a logged in user.
=> fix: Fixed login redirect to your runs when not logged in

server/assets/js/app.ts
This fixes the download_report event being handled twice in quick succession
=> fix: Double downloads [PT-188849403]

server/lib/report_server/reports/athena/learner_data.ex, server/lib/report_server/reports/athena/shared_queries.ex, server/lib/report_server/reports/athena/student_actions_report.ex, server/lib/report_server/reports/athena/student_actions_with_metadata_report.ex, server/lib/report_server/reports/report_query.ex
This adds a `primary_user_id` column to the **Student Answers**, **Student Actions**, and **Student Actions with Metadata** reports.
**Student Actions** did not previously have any columns other than what is in the log data itself. For that report this PR adds the `user_id` column as well as `primary_user_id`. In order to do this the report is refactored to work like *Student Actions with Metadata** but with just the minimal 2 columns being joined on from portal data, rather than the longer list of metadata columns.
=> Add primary_user_id to reports

server/lib/report_server/reports/report_query.ex
After MySQL upgrade on staging, count of rows at the top of portal report pages is showing an error.
Seems to be because "row" is a reserved word in MySQL, which may be more strictly enforced in v8.
=> Fix error in count SQL

server/lib/report_server/post_processing/job_server.ex, server/lib/report_server/post_processing/steps/clue_link_to_work.ex, server/lib/report_server/reports/portal/resource_metrics_details_report.ex, server/lib/report_server/reports/portal/resource_metrics_summary_report.ex, server/lib/report_server/reports/portal/teacher_status_report.ex
[REPORT-16](https://concord-consortium.atlassian.net/browse/REPORT-16)
Updates Summary Metrics by Assignment, Detailed Metrics by Assignment, and Teacher Status reports to only count one student for activity by any of a students primary/secondary accounts.
Also adds the CLUE links to work postprocessing step to the Student activity with metadata report.
[REPORT-16]: https://concord-consortium.atlassian.net/browse/REPORT-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Portal metrics reports to avoid double counting

server/lib/report_server/clue.ex
Questions answered by multiple students were creating multiple rows.
=> Avoid duplicate questions

server/lib/report_server/reports/athena/learner_data.ex
This fixes a bug where the string of ids, delimited by a space and comma, was being split by comma and then used to lookup teachers in a map.  The split strings were not trimmed which caused all the teachers except the last teacher in the list to have a space.  That space then caused the lookup in the teacher map to fail, except for the last teacher which did not have a space.
=> fix: All teachers not showing in Student Actions with Metadata [REPORT-30]

server/lib/report_server/reports/athena/learner_data.ex, server/lib/report_server/reports/athena/student_actions_report.ex, server/lib/report_server/reports/portal/resource_metrics_details_report.ex, server/lib/report_server/reports/portal/resource_metrics_summary_report.ex, server/lib/report_server/reports/portal/teacher_status_report.ex, server/lib/report_server/reports/report_filter_query.ex, server/lib/report_server/reports/report_utils.ex
Previously the query was using a "NOT LIKE '%@concord.org'" filter which both caused a full table scan of the users table (which is very large in production).  This caused the query to timeout.
The change is to instead query the database separately if the exclude CC users setting is set to get a list of all teacher ids in schools with "Concord Consortium" in their name and then join against the portal teachers table and exclude those teachers from the result.  This was the original behavior of the exclude CC users checkbox in the old reports.
=> fix: Exclude CC users learner data query [REPORT-29]

server/lib/report_server/post_processing/job.ex
The default is now an empty JobOverrides struct - it was an empty tuple before the fix.  This caused a pattern matching error when the job_server called Job#run.
=> fix: Bad default value for job overrides in Job#run
