functions/src/api/helpers/lara-types.ts, functions/src/api/helpers/paths.ts, functions/src/api/import-run.ts
Not a huge change.
We expect a run to include an array of student answers.  
One other change, I made the resource key just the URI (snake-cased) for the resource.  Simpler, and human readable.
[#165937721]
https://www.pivotaltracker.com/story/show/165937721
=> Cloud Function to import LARA student runs and answers.

functions/package-lock.json, functions/package.json, functions/src/api/import-run.ts, functions/src/test/import-run.test.ts, functions/tslint.json
The Run objects saved in FireStore should not include the answers.
This  PR also adds Jest testing framework.
Extracts  a function for extracting and removing answers from the run. Test that function.
[#166766021]
https://www.pivotaltracker.com/story/show/166766021
=> Remove answers from run record.

firestore.rules
Open access to resource JSONs for signed in users.
=> Update firebase rules

firestore.rules
These were in part copied from the FireStore console.
A history of the rules is available in the web console.
[#166241028]
https://www.pivotaltracker.com/story/show/166241028
=> Add Question and Activity feedback rules.

query-creator/create-query/steps/request.js, query-creator/template.yaml
This will allow us to deploy the SAM app as an external report for the current report service.
=> Changed demo get request to real post request [#173469930]

query-creator/create-query/app.js, query-creator/create-query/steps/aws.js
Also added common generated query id
=> Added missing columns to select [#172978976]

query-creator/create-query/app.js, query-creator/create-query/steps/aws.js, query-creator/create-query/steps/firebase.js, query-creator/template.yaml, scripts/export-answers.js
- Fixed error logging code in export-answers
- Added policy statements to allow for workgroup and s3 access
- Updated SQL generator to handle interactives with TODO
- Fixed request to firebase to get resource
- Changed error response to use error key
- Added stack trace to error output [#173924040]
=> Misc fixes found for issues after initial deploy [#173924040]

firestore.rules
NOTE: The existing answer rule was updated to match what was live on report-service-dev.
=> Add rules for plugin states to enable plugin saving in AP [#174286329]

query-creator/README.md
Add the new learner fields to the readme.
=> add new learner table fields to readme

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This PR updates the Athena SQL query created in `generateSQL` so that a "submitted" column only appears for open response questions if they are marked as "required" (and hence show the submit button to the user).  When iterating through questions in the `denormalizedResource` object, we find the associated question in the `resource` object and check its `required` property.  This search should work for both a sequence and an activity.  The unit test for `generateSQL` has also been expanded to include required and not required open response questions.
Questions:
- are there other paths where we show the submit button?
- do we need to handle resources other than activity and sequence?
Generated query on activity with a required and a non-required open response question:
=> 178184910 open response submitted column

functions/src/auto-importer.ts
Previously, we were using the previous version of the answer to get the answer's metadata. This was null if it was a new answer, so new answers were not getting sync docs created for them.
=> Fix getting answer metadata for new answers

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This PR adds a submitted column for MC and image questions in the Athena query generated in `generateSQL`.  This column is only added if the question is required.
Example query:
```
WITH activities AS ( SELECT *, cardinality(questions) as num_questions FROM "report-service"."activity_structure" WHERE structure_id = 'a46a3e07-0289-4fb1-aff6-af0fb0080be8' )
SELECT
null as num_questions,
null as num_answers,
null as percent_complete,
activities.questions['open_response_447528'].prompt AS open_response_447528_text,
activities.questions['open_response_447529'].prompt AS open_response_447529_text,
null AS open_response_447529_submitted,
activities.questions['multiple_choice_13104'].prompt AS multiple_choice_13104_choice, …
```
=> add submitted column for image and multiple choice questions

query-creator/create-query/steps/aws.js
This updates the API we use to get learners from the portal with the new pagination parameter.
This relies on getting concord-consortium/rigse#1038 merged in, and having the rake task run which updates all the learners with the new `created_at` field.
=> Use new ES pagination API

.gitignore, query-creator/README.md, query-creator/env.sample.json, query-creator/samconfig.toml
this also updates the documentation, and adds a sample file to make it easier
=> configure sam local start-api to use env.json

firestore.rules, tests/student-work-rules.test.js
[#179622498]
Auth rules related to https://github.com/concord-consortium/portal-report/pull/360.
=> Support sharing with the class / context

functions/package-lock.json, functions/package.json, functions/src/auto-importer.ts
Fix bug where collaborator answer id was the same as the leader of the collaboration leading to a runtime bug when the collaborator ran the activity later as their would be duplicate answer ids.
=> Fixed set/update of collaborator answer id

functions/package-lock.json, functions/package.json, functions/src/auto-importer.ts, scripts/README.md, scripts/count.js, scripts/delete-collection.js, scripts/package.json
PT Story: https://www.pivotaltracker.com/story/show/183093627
[#183093627]
* Add a limit to `monitorSyncDocCount` query to prevent it from failing on exceedingly large record sets.
* Add logging for errors and querySnapshot size.
=> Fix incomplete usage and details reports

query-creator/create-query/app.js
The Activity Player logs the value of its sequence or activity query parameter in the activity slot in the log message.  This code checks for those parameters when mapping over the activities to query.
=> Fixed user report for AP logged activities and sequences [#183773943]

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
After some discussion with Kiley a different approach was taken for this story. New criteria can be found here: https://www.pivotaltracker.com/n/projects/2441249/stories/178476237.
=> [#178476237]: Add fields for required questions and answers in Learner Reports

researcher-reports/src/components/query-item.scss, researcher-reports/src/components/query-item.tsx
This updates the completion status to use different text colors depending on the status.  It alss disables the generate csv button until the completion status is succeeded.
=> fix: Update report completion status and generate csv button [PT-185257065]

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/test-handler.js
This adds an url column to each open response question that points to the portal dashboard so that researchers can listen to audio responses.
=> feat: Add url column for open response questions [PT-181870149]

server/config/dev.exs, server/config/runtime.exs, server/lib/report_server_web/live/report_live/index.ex, server/lib/report_server_web/token_service.ex
This mirrors what the existing report-service client app does.
=> fix: Remove env from config and instead base it on portal url [PT-187509988]

server/assets/js/app.js, server/lib/report_server_web/aws.ex, server/lib/report_server_web/live/report_live/index.ex, server/lib/report_server_web/live/report_live/index.html.heex, server/lib/report_server_web/live/report_live/query.ex, server/lib/report_server_web/token_service.ex
This uses faked responses from the portal and AWS to allow for faster development and test work.
=> feat: Added demo mode to server [PT-187514645]

functions/src/api/get-answer.ts, functions/src/index.ts
This is needed by the audio translation report post processing to determine if the answer has audio and where the path to the audio file.
=> feat: Add report-service api endpoint to return full answer document [PT-187486891]

server/config/dev.exs, server/config/runtime.exs, server/lib/report_server_web/report_service.ex
This will be used by the report post processing to get the answer from the report service api.
=> feat: Added report_service module to server [PT-187486891]

server/docker-compose.yml
This also fixes a runtime error in the docker-compose.yml file - the quotes were not needed
=> chore: Update docker-compose.yml with new environment variables [PT-187621691]

server/lib/report_server_web/live/report_live/query.ex
This updates the button text to use URL instead of Url.
=> fix: Change Url to URL in report-server UI [PT-187621671]

server/lib/report_server/post_processing/job.ex, server/lib/report_server/post_processing/steps/demo_add_answer_length.ex, server/lib/report_server/post_processing/steps/demo_upper_case.ex, server/lib/report_server/post_processing/steps/has_audio.ex, server/lib/report_server/post_processing/steps/transcribe_audio.ex
This copies the prompt header from the open response question to all the new columns added in the post processing steps.
=> fix: Copy prompt headers to new report columns [PT-187644206]

query-creator/create-query/steps/aws.js, query-creator/create-query/tests/unit/generated-sql.js, query-creator/create-query/tests/unit/test-handler.js
This also adds missing tests for the log reports.
=> feat: Remove log data username in wide learner logs [PT-187653588]

server/README.md
README updates:
* Add info on asdf plugins, ssh tunnel
* Fix lint warnings
=> README updates

server/lib/report_server/portal_dbs.ex
For some reason Elixir Date objects don't compare properly with <, > etc.
So provide a special case to sort them.
=> Fix bug where dates don't sort properly

server/lib/report_server/reports/report.ex, server/lib/report_server/reports/resource_metrics_details.ex, server/lib/report_server/reports/resource_metrics_summary.ex, server/lib/report_server/reports/teacher_status.ex
This will cut down on the boilerplate in the reports.
=> feat: Added __using__ macro to reports

server/lib/report_server/reports/tree.ex
The root slug was not being searched.
=> fix: Bug in tree search for root node

server/docs/cohort-schema.md, server/lib/report_server/reports/report.ex, server/lib/report_server/reports/report_filter.ex, server/lib/report_server/reports/report_filter_query.ex, server/lib/report_server/reports/report_query.ex, server/lib/report_server/reports/resource_metrics_details.ex, server/lib/report_server/reports/resource_metrics_summary.ex, server/lib/report_server/reports/tbd_report.ex, server/lib/report_server/reports/teacher_status.ex, server/lib/report_server/reports/tree.ex, server/lib/report_server_web/components/core_components.ex, server/lib/report_server_web/components/custom_components.ex, server/lib/report_server_web/live/new_report_live/form.ex, server/lib/report_server_web/live/new_report_live/form.html.heex, server/lib/report_server_web/live/new_report_live/index.html.heex
Added dynamic filter queries and updated report tree with TBD report placeholders.
=> feat: Added filter queries [PT-188527665]

server/lib/report_server/reports/report.ex, server/lib/report_server/reports/report_filter.ex, server/lib/report_server/reports/report_query.ex, server/lib/report_server/reports/resource_metrics_details.ex, server/lib/report_server/reports/resource_metrics_summary.ex, server/lib/report_server/reports/teacher_status.ex, server/lib/report_server_web/live/new_report_live/form.ex, server/lib/report_server_web/live/new_report_live/form.html.heex
This adds date pickers to the UI, and filters the three existing queries using those dates to bound `last_run`.
Probably needs some tweaks but ready for a review to see if it's on the right track.
=> First draft of date filtering

server/README.md, server/lib/report_server/accounts/user.ex, server/lib/report_server/portal_dbs.ex, server/lib/report_server/reports.ex, server/lib/report_server/reports/report.ex, server/lib/report_server/reports/report_filter.ex, server/lib/report_server/reports/report_run.ex, server/lib/report_server/types/ecto_report_filter.ex, server/lib/report_server_web/components/custom_components.ex, server/lib/report_server_web/live/new_report_live/auth.ex, server/lib/report_server_web/live/new_report_live/form.ex, server/lib/report_server_web/live/new_report_live/form.html.heex, server/lib/report_server_web/live/new_report_live/index.ex, server/lib/report_server_web/live/new_report_live/index.html.heex, server/lib/report_server_web/live/report_run_live/index.ex, server/lib/report_server_web/live/report_run_live/index.html.heex, server/lib/report_server_web/live/report_run_live/show.ex, server/lib/report_server_web/live/report_run_live/show.html.heex, server/lib/report_server_web/router.ex, server/priv/repo/migrations/20241120113001_create_report_runs.exs, server/test/report_server/reports_test.exs, server/test/support/fixtures/reports_fixtures.ex
This adds a new table in the database that saves report runs and two new liveview pages that list report runs and show a report run.
=> feat: Save report runs [PT-188507981]

server/lib/report_server_web/live/new_report_live/form.ex, server/lib/report_server_web/live/new_report_live/form.html.heex
Update/set the live_select list of options when the filter type is changed.
Put date filters on one line.
=> Filter UI improvements

server/lib/report_server_web/live/codap_plugin_live/index.ex
This also gets rid of staging in the plugin (which was already commented out).
=> fix: Re-enable ngss server in CODAP plugin

server/lib/report_server/reports/athena/student_actions_report.ex, server/lib/report_server/reports/athena/teacher_actions_report.ex, server/lib/report_server/reports/portal/resource_metrics_details_report.ex, server/lib/report_server/reports/portal/resource_metrics_summary_report.ex, server/lib/report_server/reports/portal/teacher_status_report.ex, server/lib/report_server/reports/tree.ex
This moves the portal and athena reports into subfolders for better organization and appends "Report" to the report modules.
=> dev: Reorganize reports into sub-folders

server/lib/report_server/reports/athena/learner_data.ex, server/lib/report_server/reports/portal/resource_metrics_summary_report.ex, server/lib/report_server/reports/report_filter.ex, server/lib/report_server/reports/report_utils.ex
Also fixed a couple of missed compiler warnings about unused variables and removed a debug IO.inspect that was left in the code.
=> fix: Reports broken when filter_list is nil

server/lib/report_server/reports/athena/learner_data.ex, server/lib/report_server/reports/portal/resource_metrics_details_report.ex, server/lib/report_server/reports/portal/resource_metrics_summary_report.ex, server/lib/report_server/reports/portal/teacher_status_report.ex, server/lib/report_server/reports/report_filter.ex, server/lib/report_server/reports/report_filter_query.ex, server/lib/report_server/reports/report_utils.ex, server/lib/report_server_web/components/custom_components.ex, server/lib/report_server_web/live/new_report_live/form.ex, server/lib/report_server_web/live/new_report_live/form.html.heex
PT-188645467
Add a checkbox and update queries to exclude teachers with @concord.org emails.
=> Add exclude checkbox & support

server/config/dev.exs, server/config/runtime.exs, server/lib/report_server/athena_db.ex, server/lib/report_server/portal_report.ex, server/lib/report_server/post_processing/steps/glossary_data.ex, server/lib/report_server/post_processing/steps/helpers.ex, server/lib/report_server/report_service.ex, server/lib/report_server/reports/athena/athena_config.ex, server/lib/report_server/reports/athena/learner_data.ex, server/lib/report_server/reports/athena/resource_data.ex, server/lib/report_server/reports/athena/shared_queries.ex, server/lib/report_server/reports/athena/student_answers_report.ex, server/lib/report_server/reports/athena/student_assignment_usage_report.ex, server/lib/report_server/reports/report_query.ex, server/lib/report_server/reports/tree.ex, server/mix.exs
Added the details and usage reports, converted from the JavsScript version to Elixir.
This also moves the `portal_report.ex` and `report_service.ex` files to the `report_server` directory from the `report_server_web` directory.
=> feat: Added details and usage reports [PT-188527607] [PT-188527655]

server/lib/report_server/athena_db.ex
Athena has a max sql query size of 256KB which should be checked before the query is submitted to Athena.
=> feat: Add check for max sql length [PT-188748565]

server/lib/report_server/post_processing/job.ex, server/lib/report_server/post_processing/job_params.ex, server/lib/report_server/post_processing/job_server.ex, server/lib/report_server/post_processing/step.ex, server/lib/report_server/post_processing/steps/clue_link_to_work.ex
This required post processing of the report to extract the learners.  The post processing is setup to allow for other future post processing steps if needed.
=> feat: Added CLUE link to work post processing step [PT-188520218]

server/README.md, server/lib/report_server_web/live/old_report_live/index.ex, server/lib/report_server_web/live/old_report_live/index.html.heex, server/lib/report_server_web/live/old_report_live/query.ex, server/lib/report_server_web/live/report_live/auth.ex, server/lib/report_server_web/live/report_live/form.ex, server/lib/report_server_web/live/report_live/index.ex, server/lib/report_server_web/live/report_live/post_processing.ex, server/lib/report_server_web/live/report_run_live/show.ex, server/lib/report_server_web/live/report_run_live/show.html.heex, server/lib/report_server_web/router.ex, server/test/report_server_web/live/report_live_test.exs
- Renamed existing ReportLive to OldReportLive
- Renamed existing NewReportLive to ReportLive
=> build: Renamed report modules to align with paths [PT-188779638]

query-creator/samconfig.toml
Updated the researcher reports url that is redirected to after the query is created to the /old-reports link.
=> build: Update report link in query-creator sam config [PT-188779638]

server/lib/report_server_web/live/page_live/home.html.heex
This fixes the homepage when there is no logged in user.
=> fix: Add user check to homepage [PT-188779638]

functions/src/api/get-student-feedback-metadata.ts, functions/src/index.ts
This returns a map of offering ids to an object that, for now, only contains the last updated at time in seconds.
=> feat: Added student feedback metadata api endpoint [PT-188732128]

server/lib/report_server/clue.ex, server/lib/report_server/reports/report_utils.ex
Fixes two issues reported in testing of REPORT-2
=> Report 2 query bug fix

server/lib/report_server/clue.ex, server/lib/report_server/reports/athena/learner_data.ex, server/lib/report_server/reports/athena/resource_data.ex
Remove check of "signed" database field - not sure why it exists because it is never set to anything but NULL.
Fix hard-coded reference to staging athena table.
Include text tiles with default 'Text N' names in CLUE answers report
Raise visibility of errors encountered while pulling CLUE resource info.
=> Fix permissions queries & clue answers report

server/lib/report_server/post_processing/job.ex, server/test/report_server/post_processing/job_test.exs, server/test/support/fixtures/job_fixtures.ex
Add a test for the post processing job
=> feat: Add post process job test [REPORT-15]
